#!/bin/bash

# lenet MNIST top-N
python3 prepare_data.py --saved-model '/torch-deepimportance/models_info/saved_models/lenet_MNIST_whole.pth' --dataset mnist --batch-size 2 --end2end --model lenet --device 'cuda:0' --top-m-neurons 6 --n-clusters 2 --csv-file lenet_mnist_t6 --inordered-dataset --logging --log-path './logs/PreLeNetMNISTTop-6'
python3 prepare_data.py --saved-model '/torch-deepimportance/models_info/saved_models/lenet_MNIST_whole.pth' --dataset mnist --batch-size 2 --end2end --model lenet --device 'cuda:0' --top-m-neurons 8 --n-clusters 2 --csv-file lenet_mnist_t8 --inordered-dataset --logging --log-path './logs/PreLeNetMNISTTop-8'
python3 prepare_data.py --saved-model '/torch-deepimportance/models_info/saved_models/lenet_MNIST_whole.pth' --dataset mnist --batch-size 2 --end2end --model lenet --device 'cuda:0' --top-m-neurons 10 --n-clusters 2 --csv-file lenet_mnist_t10 --inordered-dataset --logging --log-path './logs/PreLeNetMNISTTop-10'
python3 prepare_data.py --saved-model '/torch-deepimportance/models_info/saved_models/lenet_MNIST_whole.pth' --dataset mnist --batch-size 2 --end2end --model lenet --device 'cuda:0' --top-m-neurons 15 --n-clusters 2 --csv-file lenet_mnist_t15 --inordered-dataset --logging --log-path './logs/PreLeNetMNISTTop-15'
python3 prepare_data.py --saved-model '/torch-deepimportance/models_info/saved_models/lenet_MNIST_whole.pth' --dataset mnist --batch-size 2 --end2end --model lenet --device 'cuda:0' --top-m-neurons 20 --n-clusters 2 --csv-file lenet_mnist_t20 --inordered-dataset --logging --log-path './logs/PreLeNetMNISTTop-20'

# lenet CIFAR10 top-N
python3 prepare_data.py --saved-model '/torch-deepimportance/models_info/saved_models/lenet_CIFAR10_whole.pth' --dataset cifar10 --batch-size 2 --end2end --model lenet --device 'cuda:0' --top-m-neurons 6 --n-clusters 2 --csv-file lenet_cifar_t6 --inordered-dataset --logging --log-path './logs/PreLeNetCIFARTop-6'
python3 prepare_data.py --saved-model '/torch-deepimportance/models_info/saved_models/lenet_CIFAR10_whole.pth' --dataset cifar10 --batch-size 2 --end2end --model lenet --device 'cuda:0' --top-m-neurons 8 --n-clusters 2 --csv-file lenet_cifar_t8 --inordered-dataset --logging --log-path './logs/PreLeNetCIFARTop-8'
python3 prepare_data.py --saved-model '/torch-deepimportance/models_info/saved_models/lenet_CIFAR10_whole.pth' --dataset cifar10 --batch-size 2 --end2end --model lenet --device 'cuda:0' --top-m-neurons 10 --n-clusters 2 --csv-file lenet_cifar_t10 --inordered-dataset --logging --log-path './logs/PreLeNetCIFARTop-10'
python3 prepare_data.py --saved-model '/torch-deepimportance/models_info/saved_models/lenet_CIFAR10_whole.pth' --dataset cifar10 --batch-size 2 --end2end --model lenet --device 'cuda:0' --top-m-neurons 15 --n-clusters 2 --csv-file lenet_cifar_t15 --inordered-dataset --logging --log-path './logs/PreLeNetCIFARTop-15'
python3 prepare_data.py --saved-model '/torch-deepimportance/models_info/saved_models/lenet_CIFAR10_whole.pth' --dataset cifar10 --batch-size 2 --end2end --model lenet --device 'cuda:0' --top-m-neurons 20 --n-clusters 2 --csv-file lenet_cifar_t20 --inordered-dataset --logging --log-path './logs/PreLeNetCIFARTop-20'

# VGG16 CIFAR10 top-N
python3 prepare_data.py --saved-model '/torch-deepimportance/models_info/saved_models/vgg16_CIFAR10_whole.pth' --dataset cifar10 --batch-size 2 --end2end --model vgg16 --device 'cuda:0' --top-m-neurons 6 --n-clusters 2 --csv-file vgg16_cifar_t6 --inordered-dataset --logging --log-path './logs/PreVGG16CIFARTop-6'
python3 prepare_data.py --saved-model '/torch-deepimportance/models_info/saved_models/vgg16_CIFAR10_whole.pth' --dataset cifar10 --batch-size 2 --end2end --model vgg16 --device 'cuda:0' --top-m-neurons 8 --n-clusters 2 --csv-file vgg16_cifar_t8 --inordered-dataset --logging --log-path './logs/PreVGG16CIFARTop-8'
python3 prepare_data.py --saved-model '/torch-deepimportance/models_info/saved_models/vgg16_CIFAR10_whole.pth' --dataset cifar10 --batch-size 2 --end2end --model vgg16 --device 'cuda:0' --top-m-neurons 10 --n-clusters 2 --csv-file vgg16_cifar_t10 --inordered-dataset --logging --log-path './logs/PreVGG16CIFARTop-10'
python3 prepare_data.py --saved-model '/torch-deepimportance/models_info/saved_models/vgg16_CIFAR10_whole.pth' --dataset cifar10 --batch-size 2 --end2end --model vgg16 --device 'cuda:0' --top-m-neurons 15 --n-clusters 2 --csv-file vgg16_cifar_t15 --inordered-dataset --logging --log-path './logs/PreVGG16CIFARTop-15'
python3 prepare_data.py --saved-model '/torch-deepimportance/models_info/saved_models/vgg16_CIFAR10_whole.pth' --dataset cifar10 --batch-size 2 --end2end --model vgg16 --device 'cuda:0' --top-m-neurons 20 --n-clusters 2 --csv-file vgg16_cifar_t20 --inordered-dataset --logging --log-path './logs/PreVGG16CIFARTop-20'

# ResNet18 CIFAR10 top-N
python3 prepare_data.py --saved-model '/torch-deepimportance/models_info/saved_models/resnet18_CIFAR10_whole.pth' --dataset cifar10 --batch-size 2 --end2end --model resnet18 --device 'cuda:0' --top-m-neurons 6 --n-clusters 2 --csv-file resnet18_cifar_t6 --inordered-dataset --logging --log-path './logs/PreResNet18CIFARTop-6'
python3 prepare_data.py --saved-model '/torch-deepimportance/models_info/saved_models/resnet18_CIFAR10_whole.pth' --dataset cifar10 --batch-size 2 --end2end --model resnet18 --device 'cuda:0' --top-m-neurons 8 --n-clusters 2 --csv-file resnet18_cifar_t8 --inordered-dataset --logging --log-path './logs/PreResNet18CIFARTop-8'
python3 prepare_data.py --saved-model '/torch-deepimportance/models_info/saved_models/resnet18_CIFAR10_whole.pth' --dataset cifar10 --batch-size 2 --end2end --model resnet18 --device 'cuda:0' --top-m-neurons 10 --n-clusters 2 --csv-file resnet18_cifar_t10 --inordered-dataset --logging --log-path './logs/PreResNet18CIFARTop-10'
python3 prepare_data.py --saved-model '/torch-deepimportance/models_info/saved_models/resnet18_CIFAR10_whole.pth' --dataset cifar10 --batch-size 2 --end2end --model resnet18 --device 'cuda:0' --top-m-neurons 15 --n-clusters 2 --csv-file resnet18_cifar_t15 --inordered-dataset --logging --log-path './logs/PreResNet18CIFARTop-15'
python3 prepare_data.py --saved-model '/torch-deepimportance/models_info/saved_models/resnet18_CIFAR10_whole.pth' --dataset cifar10 --batch-size 2 --end2end --model resnet18 --device 'cuda:0' --top-m-neurons 20 --n-clusters 2 --csv-file resnet18_cifar_t20 --inordered-dataset --logging --log-path './logs/PreResNet18CIFARTop-20'